//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISOS
    {
        public int id { get; set; }
        public int Leer { get; set; }
        public int Actualizar { get; set; }
        public int Eliminar { get; set; }
        public int Rolesid { get; set; }
        public int Menuid { get; set; }
    
        public virtual MENU MENU { get; set; }
    }
}
