//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public int Rol_estado { get; set; }
        public int Rol_create { get; set; }
    }
}
